### ISSUE TITLE
directive OBJECT 写法  字段授权问题

### ISSUE THREAD

**Issue by ghost** [supperchong/egg-apollo-server#9]
@supperchong 
ts版本 我试了下报错了，是否有正确的约定书写规范？

代码段：
```js
directive @auth(requires: [Role]) on OBJECT | FIELD_DEFINITION

enum Role {
  ADMIN
  VISITOR
  VIP
}
```

报错信息：
```js
    at Master.onAppExit (/Users/yushu/Documents/project/gayhub/beast-fitness/backend/node_modules/_egg-cluster@1.25.0@egg-cluster/lib/master.js:510:21)
    at Master.emit (events.js:198:13)
    at Messenger.sendToMaster (/Users/yushu/Documents/project/gayhub/beast-fitness/backend/node_modules/_egg-cluster@1.25.0@egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/Users/yushu/Documents/project/gayhub/beast-fitness/backend/node_modules/_egg-cluster@1.25.0@egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.cluster.on (/Users/yushu/Documents/project/gayhub/beast-fitness/backend/node_modules/_egg-cluster@1.25.0@egg-cluster/lib/master.js:353:22)
    at EventEmitter.emit (events.js:203:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:190:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
name: "AppWorkerDiedError"
pid: 879
```

**Comment by supperchong** [comment]
@lizhoukai 还需要在schemaDirective.ts 实现auth Directive，例如[schemaDirective](https://github.com/supperchong/egg-apollo-server/blob/master/test/fixtures/apps/app-test/app/graphql/schemaDirectives/schemaDirective.js) ,因为你定义在 `OBJECT | FIELD_DEFINITION`,所以需要实现visitObject，visitFieldDefinition，参考[apollo/creating-directives](https://www.apollographql.com/docs/apollo-server/schema/creating-directives/)
```ts
import { defaultFieldResolver } from "graphql";
import { SchemaDirectiveVisitor } from "graphql-tools";
class AuthDirective extends SchemaDirectiveVisitor {
  visitObject(type) {
    this.ensureFieldsWrapped(type);
    type._requiredAuthRole = this.args.requires;
  }
  // Visitor methods for nested types like fields and arguments
  // also receive a details object that provides information about
  // the parent and grandparent types.
  visitFieldDefinition(field, details) {
    this.ensureFieldsWrapped(details.objectType);
    field._requiredAuthRole = this.args.requires;
  }

  ensureFieldsWrapped(objectType) {
    // Mark the GraphQLObjectType object to avoid re-wrapping:
    if (objectType._authFieldsWrapped) return;
    objectType._authFieldsWrapped = true;

    const fields = objectType.getFields();

    Object.keys(fields).forEach(fieldName => {
      const field = fields[fieldName];
      const { resolve = defaultFieldResolver } = field;
      field.resolve = async function(...args) {
        // Get the required Role from the field first, falling back
        // to the objectType if no Role is required by the field:
        const requiredRole =
          field._requiredAuthRole || objectType._requiredAuthRole;

        if (!requiredRole) {
          return resolve.apply(this, args);
        }
        console.log("requiredRole", requiredRole);
        // const context = args[2];
        // const user = await getUser(context.headers.authToken);
        // if (!user.hasRole(requiredRole)) {
        //   throw new Error("not authorized");
        // }

        return resolve.apply(this, args);
      };
    });
  }
}
module.exports = {
  auth: AuthDirective
};
```

**Comment by lizhoukai** [comment]
@supperchong 非常感谢 原来是没实现 visitObject 缘故
